-- =====================================================
-- Email Validation for UM6P Students
-- DROP and RECREATE from scratch
-- =====================================================

-- Drop existing objects
DROP TRIGGER IF EXISTS check_student_email_before_insert ON profiles;
DROP FUNCTION IF EXISTS validate_student_email();
DROP FUNCTION IF EXISTS is_email_allowed(TEXT);
DROP FUNCTION IF EXISTS import_allowed_emails(TEXT);
DROP TABLE IF EXISTS allowed_student_emails CASCADE;

-- Table to store allowed student emails
CREATE TABLE allowed_student_emails (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        email TEXT NOT NULL UNIQUE CHECK (email ~* '@um6p\.ma$'),
            student_name TEXT,
                student_number TEXT,
                    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                        added_by UUID REFERENCES profiles(id),
                            notes TEXT
                            );

                            CREATE INDEX idx_allowed_emails_email ON allowed_student_emails(LOWER(email));

                            -- Enable RLS
                            ALTER TABLE allowed_student_emails ENABLE ROW LEVEL SECURITY;

                            -- Only admins can view/manage allowed emails
                            CREATE POLICY "Only admins can manage allowed emails" ON allowed_student_emails FOR ALL USING (
                                EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                );

                                -- Function to check if email is allowed
                                CREATE OR REPLACE FUNCTION is_email_allowed(email_to_check TEXT)
                                RETURNS BOOLEAN
                                LANGUAGE plpgsql
                                SECURITY DEFINER
                                AS $$
                                BEGIN
                                    -- Check domain
                                        IF email_to_check !~* '@um6p\.ma$' THEN
                                                RETURN false;
                                                    END IF;
                                                        
                                                            -- Check whitelist
                                                                RETURN EXISTS (
                                                                        SELECT 1 
                                                                                FROM allowed_student_emails 
                                                                                        WHERE LOWER(email) = LOWER(email_to_check)
                                                                                            );
                                                                                            END;
                                                                                            $$;

                                                                                            -- Trigger to validate ONLY domain for students (not strict whitelist)
                                                                                            -- Email verification will be handled by Supabase Auth
                                                                                            CREATE OR REPLACE FUNCTION validate_student_email()
                                                                                            RETURNS TRIGGER
                                                                                            LANGUAGE plpgsql
                                                                                            AS $$
                                                                                            BEGIN
                                                                                                IF NEW.role = 'student' THEN
                                                                                                        -- Check domain only
                                                                                                                IF NEW.email !~* '@um6p\.ma$' THEN
                                                                                                                            RAISE EXCEPTION 'Student email must be from UM6P domain (@um6p.ma)';
                                                                                                                                    END IF;
                                                                                                                                            
                                                                                                                                                    -- Optional: Log non-whitelisted signups for admin review
                                                                                                                                                            IF NOT is_email_allowed(NEW.email) THEN
                                                                                                                                                                        -- Insert notification for admin to review
                                                                                                                                                                                    INSERT INTO notifications (user_id, title, message, type)
                                                                                                                                                                                                SELECT id, 
                                                                                                                                                                                                                   'New Student Signup - Review Required',
                                                                                                                                                                                                                                      'Student ' || NEW.email || ' signed up but is not in the whitelist',
                                                                                                                                                                                                                                                         'admin_review'
                                                                                                                                                                                                                                                                     FROM profiles 
                                                                                                                                                                                                                                                                                 WHERE role = 'admin'
                                                                                                                                                                                                                                                                                             LIMIT 1;
                                                                                                                                                                                                                                                                                                     END IF;
                                                                                                                                                                                                                                                                                                         END IF;
                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                 RETURN NEW;
                                                                                                                                                                                                                                                                                                                 END;
                                                                                                                                                                                                                                                                                                                 $$;

                                                                                                                                                                                                                                                                                                                 CREATE TRIGGER check_student_email_before_insert
                                                                                                                                                                                                                                                                                                                     BEFORE INSERT ON profiles
                                                                                                                                                                                                                                                                                                                         FOR EACH ROW
                                                                                                                                                                                                                                                                                                                             EXECUTE FUNCTION validate_student_email();

                                                                                                                                                                                                                                                                                                                             -- Helper function for admin to bulk import emails from CSV
                                                                                                                                                                                                                                                                                                                             CREATE OR REPLACE FUNCTION import_allowed_emails(emails_csv TEXT)
                                                                                                                                                                                                                                                                                                                             RETURNS JSON
                                                                                                                                                                                                                                                                                                                             LANGUAGE plpgsql
                                                                                                                                                                                                                                                                                                                             SECURITY DEFINER
                                                                                                                                                                                                                                                                                                                             AS $$
                                                                                                                                                                                                                                                                                                                             DECLARE
                                                                                                                                                                                                                                                                                                                                 email_row TEXT;
                                                                                                                                                                                                                                                                                                                                     email_value TEXT;
                                                                                                                                                                                                                                                                                                                                         inserted_count INTEGER := 0;
                                                                                                                                                                                                                                                                                                                                             skipped_count INTEGER := 0;
                                                                                                                                                                                                                                                                                                                                             BEGIN
                                                                                                                                                                                                                                                                                                                                                 -- Check if user is admin
                                                                                                                                                                                                                                                                                                                                                     IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
                                                                                                                                                                                                                                                                                                                                                             RETURN json_build_object('success', false, 'error', 'Admin access required');
                                                                                                                                                                                                                                                                                                                                                                 END IF;
                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                         -- Process each line
                                                                                                                                                                                                                                                                                                                                                                             FOREACH email_row IN ARRAY string_to_array(emails_csv, E'\n')
                                                                                                                                                                                                                                                                                                                                                                                 LOOP
                                                                                                                                                                                                                                                                                                                                                                                         email_value := TRIM(email_row);
                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                         -- Skip empty lines
                                                                                                                                                                                                                                                                                                                                                                                                                 IF email_value = '' THEN
                                                                                                                                                                                                                                                                                                                                                                                                                             CONTINUE;
                                                                                                                                                                                                                                                                                                                                                                                                                                     END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                     -- Validate format
                                                                                                                                                                                                                                                                                                                                                                                                                                                             IF email_value !~* '@um6p\.ma$' THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         skipped_count := skipped_count + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     CONTINUE;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             -- Insert if not exists
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     INSERT INTO allowed_student_emails (email, added_by)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             VALUES (LOWER(email_value), auth.uid())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ON CONFLICT (email) DO NOTHING;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     IF FOUND THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 inserted_count := inserted_count + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ELSE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     skipped_count := skipped_count + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 END LOOP;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         RETURN json_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'success', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'inserted', inserted_count,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'skipped', skipped_count
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $$;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     